name: HelperFunctions_Push
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  HelperFunctions_Push:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.HMGITHUB }}
  build:
    runs-on: windows-latest
    name: Update HelperFunctions Github 
    steps:

      - name: Checkout repository
        uses: actions/checkout@main
          
      - name: Build solution and generate NuGet package
        run: |  
          cd C:\Scripts\repos\hmiller10\HelperFunctions
          dotnet pack -c Release -o out  
        
      - name: Push generated package to GitHub registry
        run: nuget push C:\Scripts\repos\hmiller10\HelperFunctions\out\*.nupkg -Source "HMGithub" -SkipDuplicate
