name: Deploy Documentation
on:
  push:
    branches:
      - main
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Point this to the folder containing your .md help files
          path: './Docs' 

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
