# This is a basic workflow to help you get started with Actions
name: Publish_HelperFunctions_Module

# Controls when the workflow will run
on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  publish-to-gallery:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          path: main
      
      - name: Initialize environment
        uses: PSModule/Initialize-PSModule@main

      - name: Publish-PSModule
        uses: PSModule/Publish-PSModule@main
        env:
          NUGET_KEY: ${{ secrets.HMILLER10_PSGALLERY_APIKEY }}

permissions:
  contents: write # Required to create releases
  pull-requests: write # Required to create comments on the PRs