# This is a basic workflow to help you get started with Actions
name: Publish_HelperFunctions_Module

# Controls when the workflow will run
on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  publish-to-gallery:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          path: main
      
      - name: Install and cache PowerShell modules
        uses: potatoqualitee/psmodulecache@v6.2.1
        with:
          modules-to-cache: Microsoft.PowerShell.PSResourceGet,PSFramework,Pester::,HelperFunctions
          updatable: true
          shell: powershell

      - name: Show that the Action works
        shell: powershell
        run: |
              Get-Module -Name PSFramework, Pester, HelperFunctions -ListAvailable | Select Path
              Import-Module -Name HelperFunctions -Force
      - name: Get working directory
        run: |
          Get-ChildItem -Path ${{ github.workspace }} -Recurse
        shell: powershell

      - name: Test module
        run: |
         # Replace with your build and test commands
         #$config = [PesterConfiguration]::Default
         #$config.TestResult.Enabled = $true
         #$config.Run.Exit = $true
         #$config.CodeCoverage.Enabled = $true
         Invoke-Pester -Path (Join-Path ${{ github.workspace }} "main\Tests") -Output Detailed -ErrorAction 'Continue' #-CI -Configuration $config
        shell: powershell

      - name: Publish to PowerShell Gallery
        env:
          NUGET_KEY: ${{ secrets.HMILLER10_PSGALLERY_APIKEY }}
          #BUILDVER: '2.8.6'
          
        run: |
          Publish-Module -Path (Join-Path ${{ github.workspace }} "main\HelperFunctions.psd1") -NuGetApiKey $env:NUGET_KEY -Verbose
          #Publish-PSResource -Path (Join-Path ${{ github.workspace }} "main\HelperFunctions.psd1") -Repository PSGallery -ApiKey $env:NUGET_KEY -Confirm:$false -Verbose
        shell: powershell  
