 - name: Publish Module to PowerShell Gallery
        uses: hmmiller10/publish-powershell-module-action@v20
        id: publish-module
        with:
          NuGetApiKey: ${{ secrets.'HM_RW_Secret' }}