
name: Publish_HelperFunctions_Module

permissions:
  contents: read
# Controls when the workflow will run
on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  publish-to-gallery:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          path: main

      - name: Install and cache PowerShell modules
        uses: potatoqualitee/psmodulecache@v6.2.1
        with:
          modules-to-cache: PSFramework,Pester::,HelperFunctions, Microsoft.PowerShell.PSResourceGet
          updatable: true
          shell: powershell

      - name: Show that the Action works
        shell: powershell
        run: |
          Get-Module -Name PSFramework, Pester, HelperFunctions,Microsoft.PowerShell.PSResourceGet -ListAvailable | Select-Object -ExpandProperty Path
          Import-Module -Name HelperFunctions -Force

      - name: Get working directory
        run: |
          Get-ChildItem -Path ${{ github.workspace }} -Recurse
        shell: powershell

      - name: Test module
        run: |
         Invoke-Pester -Path (Join-Path ${{ github.workspace }} "\main\Tests") -Output Detailed -ErrorAction 'Continue'
        shell: powershell

      - name: Publish to PowerShell Gallery
        env:
          NUGET_KEY: ${{ secrets.POWERSHELLGALLERY }}

        run: |
          $modulePath = Join-Path ${{ github.workspace }} "\Main"
          Set-Location -Path $modulePath
          Publish-Module -Path .  -NuGetApiKey $env:NUGET_KEY -Repository PSGallery -Verbose
        shell: powershell