# This is a basic workflow to help you get started with Actions
name: Publish HelperFunctions Module

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches:
      - main 

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      #- name: Set up PowerShell
      #  uses: microsoft/powershell@v5

      - name: Build and test module
        run: |
         # Replace with your build and test commands
         # Example:
          Invoke-Pester -Path "C:\Scripts\Repos\hmiller10\HelperFunctions\Tests"

      - name: Publish to PowerShell Gallery
        env:
          HMILLER10_PSGALLERY_APIKEY: ${{ secrets.HMILLER10_PSGALLERY_APIKEY }}
          
        run: |
          Publish-Module -Path "C:\Scripts\Repos\hmiller10\HelperFunctions" -Name "HelperFunctions" -NuGetApiKey $env:HMILLER10_PSGALLERY_APIKEY -Repository PSGallery