# This is a basic workflow to help you get started with Actions
name: Publish_HelperFunctions_Module

# Controls when the workflow will run
on:
  
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  publish-to-gallery:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and test module
        run: |
         # Replace with your build and test commands
         Invoke-Pester -Path .\Tests
        shell: powershell
          

      - name: Publish to PowerShell Gallery

        env:
          NUGET_KEY: ${{ secrets.HMILLER10_PSGALLERY_APIKEY }}
          BUILDVER: '2.3.0'
          
        run: |
          Publish-Module -Path .\Code -Name "HelperFunctions" -NuGetApiKey $env:HMILLER10_PSGALLERY_APIKEY -Repository PSGallery
        shell: powershell
          