 name: Publish Module to PowerShell Gallery
        uses: hmiller10/publish-powershell-module-action@v*
        id: publish-module
        with:
          NuGetApiKey: ${{ secrets.HMILLER10_PSGALLERY_APIKEY }}