# This is a basic workflow to help you get started with Actions
name: Publish_HelperFunctions_Module

# Controls when the workflow will run
on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  publish-to-gallery:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          path: main
      
      - name: Install and cache PowerShell modules
        uses: potatoqualitee/psmodulecache@v6.0
        with:
          modules-to-cache: PSFramework,Pester::,HelperFunctions
          updatable: true
          shell: powershell
 
      - name: Show that the Action works
        shell: powershell
        run: |
              Get-Module -Name PSFramework, Pester, HelperFunctions -ListAvailable | Select Path
              Import-Module -Name HelperFunctions -Force

      - name: Get working directory
        run: |
          Get-ChildItem -Path ${{ github.workspace }} -Recurse
          $WorkingDir = Get-ChildItem -Path ${{ github.workspace }} -Recurse
        shell: powershell

      - name: Test module
        run: |
         #Invoke-Pester -Path (Join-Path ${{ github.workspace }} "main\Tests") -Output Detailed -ErrorAction 'Continue'
        shell: powershell

      - name: Publish to PowerShell Gallery
        env:
          DESCRIPTION: ${{ github.event.description }}
          PSGALLERY_KEY: ${{ secrets.HMILLER10_PSGALLERY_APIKEY }}
          #BUILDVER: '2.7.1'
          
        run: |
        	$modulePath = "{0}\{1}\{2}\{3}" -f $WorkingDir, "main", "code", "HelperFunctions.psd1"
          #Publish-Module -Path (Join-Path ${{ github.workspace }} "main\Code\HelperFunctions.psd1") -NuGetApiKey $env:PSGALLERY_KEY -Repository PSGallery -Verbose -ErrorAction 'Continue'
          Publish-Module -Path $modulePath -NuGetApiKey $env:PSGALLERY_KEY -Repository PSGallery -Verbose -ErrorAction 'Continue'
        shell: powershell
