name: Pull Request Merge

on:
  pull_request:
    types:
      - closed

  workflow_dispatch:

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Publish module to PowerShell Gallery
        run: |
          env:
          NUGET_KEY: ${{ secrets.HMILLER10_PSGALLERY_APIKEY }}
          Publish-Module -Path . -Repository PSGallery -NuGetApiKey $env:NUGET_KEY
        shell: pwsh
